server:
  port: 8585

jmx:
  rmi:
    port: 7040
    host: localhost

spring:
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: validate

    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: false
    properties:
      hibernate:
        temp:
          # Fix Postgres JPA Error:
          # Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
          use_jdbc_metadata_defaults: false

  datasource:
    url: jdbc:postgresql://localhost:5432/ggdb
    driver-class-name: org.postgresql.Driver
    testWhileIdle: true
    validationQuery: "SELECT 1"
    username: postgres
    password: postgres

gaisclient:
    group: 'ООО "ГЛОСАВ"'
    #host: 193.232.47.4  # external public Glonass - 193.232.47.4
    host: 10.77.205.98 # internal via Glosav - Glonass VipNet
    port: 19991
    login: glosavintegration
    password: glvI17_Gr0n
    transfer:
      job:
        interval: 60
    ssl:
        enabled: true
        #truststore: /home/asergeev/work/glosavcluster/gais-gateway/etc/jks/okp_new.jks
        #truststore: /home/asergeev/work/glosavcluster/gais-gateway/etc/jks/era.jks
        truststore: /home/asergeev/gais-gateway/etc/jks/era_new.jks

        passphrase: okp_pass
    ts:
        color: #00ffff
        icon: 7
logging:
  level:
    ru.glosav.gais.gateway: debug

---
spring:
  profiles: home-mac

gaisclient:
  host: 193.232.47.4  # external public Glonass - 193.232.47.4
  ssl:
    truststore: /Users/asergeev/work/glosavcluster/gais-gateway/etc/jks/era_new.jks